### ISSUE TITLE
Sending custom message without UMM

### ISSUE THREAD

**Issue by VishalWaman** [botpress/botpress-platform-webchat#23]
>  bp.hear({ type: /message|text/i, platform: 'webchat', text: /.+/ }, (event, next) => {
        event.reply(event.user.id,"hi");
      });

I want to send custom message with UMM, something like 

> bp.messenger.sendText(event.user.id, "Thanks for sharing you location..");

**Comment by slvnperron** [comment]
@VishalWaman Why do you need to send a message without UMM?

**Comment by VishalWaman** [comment]
We have backend messages located in DB, we need to full them and send it..

**Comment by VishalWaman** [comment]
Some days back i tried sending message without UMM, it was some think  like blelow

> event.send("<userid>","<text message>");

Something similar

**Comment by slvnperron** [comment]
You can create a UMM bloc that contains only a text variable:

```
text:
  text: {{{text}}}
```

Then you can send whatever you want: `event.reply('#text', { text: "Build your text" })`

**Comment by VishalWaman** [comment]
Cool, let me try this one..
