### ISSUE TITLE
Can't install module

### ISSUE THREAD

**Issue by QurQuma** [botpress/botpress-platform-webchat#26]
Hello,
  I'm trying to intall module (npm, botpress) but the result is always:
 ERR npm
[botpress]       ERR
[botpress]       ERR WARN
[botpress]       ERR  react-codemirror@1.0.0 requires a peer of react@>=15.5 <16 but none is installed. You must install peer dependencies yourself.

[botpress]       ERR npm
[botpress]       ERR
[botpress]       ERR WARN
[botpress]       ERR  react-codemirror@1.0.0 requires a peer of react-dom@>=15.5 <16 but none is installed. You must install peer dependencies yourself.

[botpress]       ERR npm
[botpress]       ERR
[botpress]       ERR WARN
[botpress]       ERR  react-jsonschema-form@0.49.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.

[botpress]       ERR npm
[botpress]       ERR
[botpress]       ERR WARN
[botpress]       ERR  qurquma@1.0.0 No description

[botpress]       ERR npm
[botpress]       ERR
[botpress]       ERR WARN
[botpress]       ERR  qurquma@1.0.0 No repository field.

[botpress]       ERR npm
[botpress]       ERR
[botpress]       ERR WARN
[botpress]       ERR
[botpress]       ERR optional
[botpress]       ERR  SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):

[botpress]       ERR npm
[botpress]       ERR
[botpress]       ERR WARN
[botpress]       ERR
[botpress]       ERR notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

What's going wrong?
Thanks,
QurQuma

**Comment by slvnperron** [comment]
@QurQuma These are all warnings, it should be installed
