### ISSUE TITLE
Sending custom data from website to the application

### ISSUE THREAD

**Issue by IamLance** [botpress/botpress-platform-webchat#31]
Hi,

                  Is there any way we can send custom data from the parent website where we embedded the webchat to the backend code of the chat. We see that we can open the window programmatically using window.botpressChat('show') and was wondering if there are other functions we can use like sending custom data to the botpress chat

Thank you for the help!

**Comment by saniko** [comment]
And from the chat to the parent site, so that the hosting site can listen to some prop on the botpressChat object

**Comment by slvnperron** [comment]
Looping you in as you worked in this recently! @epaminond

**Comment by epaminond** [comment]
@IamLance , as of now you can call [window.botpressWebChat.sendEvent(payload)](https://github.com/botpress/botpress-platform-webchat/blob/master/src/inject.js#L24) on parent website and it [gets handled](https://github.com/botpress/botpress-platform-webchat/blob/master/src/views/web/index.jsx#L94) in webchat. What kind of data are you trying to pass?

@saniko , from chat you can send events to parent site via `window.parent.postMessage()`.

**Comment by IamLance** [comment]
We are trying to pass custom JSON data in the background. these are custom session variables for example name of a login user.

**Comment by epaminond** [comment]
@IamLance , I think you can pass them via `sendEvent`.

**Comment by IamLance** [comment]
Yes thank you. Closing this issue!
