### ISSUE TITLE
Cannot get length of null when starting

### ISSUE THREAD

**Issue by emirotin** [botpress/botpress-platform-webchat#34]
I've noticed an issue in `fetchCurrentConversation` with the recent develop/x branch of botpress.
It's likely happening here `this.state.conversations.length` which is kinda expected that `conversations` can be `null`, but I haven't seen it before.

Guys, have you?

**Comment by slvnperron** [comment]
Thanks. Will let @epaminond have a look but currentConversation can indeed be null if not existent.

**Comment by emirotin** [comment]
The problem is with `conversations` being null in my understanding, and then the code tries to access `.length` on it

**Comment by epaminond** [comment]
OK, will check it.

**Comment by slvnperron** [comment]
Ok if conversations is null we should fix the server to return empty array
(assuming the null comes from there)

**Comment by epaminond** [comment]
@slvnperron , fixed that: https://github.com/botpress/botpress-platform-webchat/pull/35
An issue could occur after [moving](https://github.com/botpress/botpress-platform-webchat/commit/761e6be4a6409d5398b36d379d9cedf5db5b5c87#diff-75f002f58cf359ea846046ba44d3ea53R211) settings to the client. It could cause delay in fetching conversation previously while now it tries to fetch conversation earlier and it appears conversation id may not be there by that time.

**Comment by slvnperron** [comment]
@epaminond Do you mean there's a potential race condition? Could you check if that's the case?
Thanks for fixing this!

**Comment by epaminond** [comment]
@slvnperron , I don't mean that. That comment was there since initial commit 5 months ago.
This isn't an actual race condition - it's just (redundant?) handling of situation when we user changes conversation faster then we fetch it. For me that condition never occurred.

**Comment by slvnperron** [comment]
@epaminond Oh, ok get it, thanks
