### ISSUE TITLE
Master broken

### ISSUE THREAD

**Issue by slvnperron** [botpress/botpress-platform-webchat#37]
A fresh install of the master gives me the following error when loading it in external mode:

![image](https://user-images.githubusercontent.com/1315508/35457348-98aa27b2-02a6-11e8-9fd8-62815724d27f.png)

Also the embedded chat loads but somehow the messages don't show up in real-time, I need to refresh the page to see them

**Comment by slvnperron** [comment]
Adding `options={}` at the end helps (i.e. it loads) but it should't be required. Also the chat doesn't work in real-time, i.e. the socket connection seems to be broken

**Comment by epaminond** [comment]
I've opened a https://github.com/botpress/botpress-platform-webchat/pull/38 making options not required.
As for websocket not sure. Getting weird error `[UMM] Bloc not defined (#welcome)` (while it is defined).

**Comment by slvnperron** [comment]
@epaminond Are you running the [`dev-bot`](https://github.com/botpress/botpress/tree/develop/x/dev-bot) ?

**Comment by epaminond** [comment]
@slvnperron , now - yes. ))

**Comment by slvnperron** [comment]
Re-opening for the socket issue

**Comment by epaminond** [comment]
@slvnperron , an issue seems to come from [extracting selectors](https://github.com/botpress/botpress/commit/fd5ed1f7eea31a9410941a58635964580662fd7d) and here's a magic fix that works for me: https://github.com/botpress/botpress/pull/407. Let me know if that works for you.

@emirotin , not sure why this is an issue and how this fix helped. Any ideas? :blush:

**Comment by emirotin** [comment]
This doesn't make any sense to me o_O
I'll try to look into it today

**Comment by slvnperron** [comment]
BTW still getting this

![image](https://user-images.githubusercontent.com/1315508/35478183-357ce5ae-03a4-11e8-8859-259e219b8f51.png)

**Comment by slvnperron** [comment]
@epaminond I need to revert PR https://github.com/botpress/botpress/pull/407

This broke again the web interface (doesn't render at all like the last time)

**Comment by slvnperron** [comment]
OK, found the issue. There's basically two EventBus being instantiated and only the first one receives the events. Investigating further.

![image](https://user-images.githubusercontent.com/1315508/35478354-f66f3542-03a8-11e8-9723-a48eb1b93b04.png)

**Comment by slvnperron** [comment]
See botpress/botpress#025088a2ee9ea78248ff669fc85d7937fd458bd0

**Comment by epaminond** [comment]
@slvnperron , that's weird. I've made testing for https://github.com/botpress/botpress/pull/407 and it worked. :anguished:
