### ISSUE TITLE
Issue with Web View (new script-tags)

### ISSUE THREAD

**Issue by to7be** [botpress/botpress-platform-webchat#39]
I tried to embed my bot into a website by following the the readme's instructions:

```
<script src="https://my-bot.herokuapp.com/api/botpress-platform-webchat/inject.js"></script>
<script>window.botpressWebChat.init({ host: 'my-bot.herokuapp.com' })</script>
```

But the browser's console spits out errors:
> (index):18 Uncaught TypeError: Cannot read property 'init' of undefined
    at (index):18
(anonymous) @ (index):18
inject.js:10 GET http://**host-of-website**/api/botpress-platform-webchat/inject.css net::ERR_ABORTED
injectDOMElement @ inject.js:10
(anonymous) @ inject.js:28
inject.js:10 GET http://**host-of-website**/lite/?m=platform-webchat&v=embedded 404 (Not Found)

In my case the provided host from the script tags is not correctly passed and the script takes the current host where it's running instead (website).

Using the "old" way of implementing works for me:

```
<script>
   window.botpressSettings = {
       hostname: "my-bot.herokuapp.com"
   };
</script>
<script>
   !function(){function t(){var t=n.createElement("script");t.type="text/javascript",t.async=!0,t.src="https://"+a.hostname+"/api/botpress-platform-webchat/inject.js";var e=n.getElementsByTagName("script")[0];e.parentNode.insertBefore(t,e)}var e=window,a=e.botpressSettings,n=document;e.attachEvent?e.attachEvent("onload",t):e.addEventListener("load",t,!1)}();
</script>
```

What am I missing?

**Comment by slvnperron** [comment]
@epaminond

**Comment by epaminond** [comment]
@to7be , `window.botpressWebChat.init` interface was introduced in `1.0.0-beta1`. Are you sure you are using latest codebase?

**Comment by to7be** [comment]
Shame on me! I installed the module at the same day so I never considered that this could be the problem. I guess betas are not installed automatically.
